"""Deterministic LaTeX tables for the AGEL0206 paper (2026-06-14).

Reads EVERY number from the single source of truth (`results/PAPER_VALUES.json`,
written by `scripts/paper_values.py`) — nothing is hand-typed here. Emits:

  results/key_results_table.tex   — headline measurements/results (AASTeX deluxetable)

The companion Sersic-parameter appendix table is produced by
`scripts/sersic_parameter_table.py` → `results/sersic_parameter_table.tex`
(also registry-deterministic for its cosmology-dependent kpc column).

Run from the repo root:  python scripts/make_latex_tables.py
"""
from __future__ import annotations
import json
from pathlib import Path
from astropy.coordinates import SkyCoord
import astropy.units as u

REPO = Path(__file__).resolve().parents[1]
PV = json.load(open(REPO / 'results' / 'PAPER_VALUES.json'))


def v(*keys):
    """Pull a nested {'value':..} leaf from the registry."""
    d = PV
    for k in keys:
        d = d[k]
    return d


def key_results_tex() -> str:
    se, seb = PV['sigma_e'], PV['sigma_e_budget']
    M, Mb = PV['logMstar'], PV['logMstar_budget']
    R, C, P, L = PV['R_e'], PV['constants'], PV['photometry'], PV['lens_model']

    c = SkyCoord(C['ra_deg']['value'] * u.deg, C['dec_deg']['value'] * u.deg)
    ra = c.ra.to_string(unit=u.hour, sep=':', precision=2, pad=True)
    dec = c.dec.to_string(unit=u.deg, sep=':', precision=1, alwayssign=True, pad=True)

    sig = se['central']['value']
    s_lo, s_hi = se['stat_lo']['value'], se['stat_hi']['value']
    s_sys = seb['sys_quad']['value']
    re_as, re_kpc, re_sys = R['central_arcsec']['value'], R['central_kpc']['value'], R['method_sys_arcsec']['value']
    lm, lm_hi, lm_lo = M['central_10pct']['value'], M['err_hi_10pct']['value'], M['stat_lo_10pct']['value']
    lm_sys = M['sys_quad_dex']['value']            # masking + apcorr-model + SFH-prior (already spans cD-envelope direction)
    floor = P['mag_floor_err']['value']
    mbh, mbh_lo, mbh_hi = L['M_BH']['value'], L['M_BH']['err_lo'], L['M_BH']['err_hi']
    lmbh, lmbh_lo, lmbh_hi = L['logM_BH']['value'], L['logM_BH']['err_lo'], L['logM_BH']['err_hi']
    thE, gam, gam_e = L['theta_E']['value'], L['gamma']['value'], L['gamma']['err_sym']
    mbh_over_mstar = 10 ** (lmbh - lm)
    mbh_mant = mbh / 1e8

    def sec(title):
        return rf'\multicolumn{{2}}{{l}}{{\textbf{{{title}}}}} \\'

    rows = []
    rows.append(r'\hline')
    rows.append(sec('System'))
    rows.append(rf'R.A. (J2000) & {ra} \\')
    rows.append(rf'Decl. (J2000) & {dec} \\')
    rows.append(rf'Deflector redshift, $z_{{\rm defl}}$ & {C["z_deflector"]["value"]:.5f} \\')
    rows.append(rf'Source redshift, $z_{{\rm src}}$ & {C["z_source"]["value"]:.5f} \\')
    rows.append(rf'Scale at $z_{{\rm defl}}$ & {C["kpc_per_arcsec"]["value"]:.3f} kpc\,arcsec$^{{-1}}$ \\')

    rows.append(r'\hline')
    rows.append(sec('Stellar kinematics'))
    # rounding matched to Figure 2: sigma_e as integers (km/s)
    rows.append(rf'$\sigma_e(<\!R_e)$ & '
                rf'$ {sig:.0f}^{{+{s_hi:.0f}}}_{{-{s_lo:.0f}}}\,({{\rm stat}}) \pm {s_sys:.0f}\,({{\rm sys}})$ km\,s$^{{-1}}$ \\')

    rows.append(r'\hline')
    rows.append(sec('Photometry \& stellar mass'))
    rows.append(rf'Effective radius, $R_e$ & ${re_as:.2f}\pm{re_sys:.2f}$ arcsec $=\ {re_kpc:.2f}$ kpc \\')
    for bn, b in P['bands'].items():
        nm = bn.replace('_', r'\_')
        rows.append(rf'$m_{{\rm {nm}}}$ (AB) & ${b["m_AB_total"]:.2f}\pm{floor:.2f}$ \\')
    # M* one decimal, stat/sys separated (sys = masking + apcorr-model + SFH-prior, quadrature);
    # symmetric ± when stat_hi and stat_lo round equal at this precision (matches Figure 2).
    if round(lm_hi, 1) == round(lm_lo, 1):
        lm_stat = rf'\pm {lm_hi:.1f}'
    else:
        lm_stat = rf'^{{+{lm_hi:.1f}}}_{{-{lm_lo:.1f}}}'
    rows.append(rf'$\log(M_\star/M_\odot)$ & '
                rf'$ {lm:.1f}{lm_stat}\,({{\rm stat}}) \pm {lm_sys:.1f}\,({{\rm sys}})$ \\')
    A = PV['sed']['mass_weighted_age']
    rows.append(rf'Mass-weighted age & '
                rf'$ {A["value"]:.1f}^{{+{A["err_hi"]:.1f}}}_{{-{A["err_lo"]:.1f}}}$ Gyr \\')

    rows.append(r'\hline')
    rows.append(sec('Lens model (provisional)'))
    rows.append(rf'Black-hole mass, $M_\bullet$ & '
                rf'$ {mbh_mant:.1f}^{{+{mbh_hi/1e8:.1f}}}_{{-{mbh_lo/1e8:.1f}}} \times 10^{{8}}\,M_\odot$ \\')
    rows.append(rf'$\log(M_\bullet/M_\odot)$ & $ {lmbh:.2f}^{{+{lmbh_hi:.2f}}}_{{-{lmbh_lo:.2f}}}$ \\')
    rows.append(rf'$M_\bullet/M_\star$ & ${mbh_over_mstar*1e3:.1f}\times 10^{{-3}}$ \\')
    rows.append(rf'Einstein radius, $\theta_E$ & ${thE:.2f}$ arcsec \\')
    rows.append(rf'Total density slope, $\gamma$ & ${gam:.2f}\pm{gam_e:.2f}$ \\')
    rows.append(r'\hline')

    body = '\n'.join(rows)
    return rf"""% Generated by scripts/make_latex_tables.py from results/PAPER_VALUES.json — do NOT hand-edit.
% Plain single-column table (stays within one column of a two-column AASTeX article).
\begin{{table}}
\centering
\caption{{Key measurements and results for the deflector of AGEL\,J020613$-$011417
(Planck\,2015, $H_0=67.7$, $\Omega_m=0.302$). Lens-model values are provisional
(Ferrami et al., in prep.).\label{{tab:keyresults}}}}
\begin{{tabular}}{{ll}}
{body}
\end{{tabular}}
\end{{table}}
"""


def main():
    out = REPO / 'results' / 'key_results_table.tex'
    out.write_text(key_results_tex())
    print(f'wrote {out}')
    print(key_results_tex())


if __name__ == '__main__':
    main()
